package com.clo.accloss.estadistica.domain.mappers

import com.clo.accloss.estadistica.data.remote.model.EstadisticaResponse
import com.clo.accloss.estadistica.domain.model.Estadistica
import com.clo.accloss.Estadistica as EstadisticaEntity

fun EstadisticaEntity.toDomain(): Estadistica = Estadistica(
    clivisit = clivisit,
    cntclientes = cntclientes,
    cntfacturas = cntfacturas,
    cntpedidos = cntpedidos,
    cntrecl = cntrecl,
    codcoord = codcoord,
    defdolTotneto = defdolTotneto,
    devdolTotneto = devdolTotneto,
    fechaEstad = fechaEstad,
    lomMontovtas = lomMontovtas,
    lomPrcvisit = lomPrcvisit,
    lomPrcvtas = lomPrcvtas,
    mtofacturas = mtofacturas,
    mtopedidos = mtopedidos,
    mtorecl = mtorecl,
    metavend = metavend,
    nombrevend = nombrevend,
    nomcoord = nomcoord,
    ppgdolTotneto = ppgdolTotneto,
    prcmeta = prcmeta,
    prcvisitas = prcvisitas,
    rlomMontovtas = rlomMontovtas,
    rlomPrcvisit = rlomPrcvisit,
    rlomPrcvtas = rlomPrcvtas,
    totdolcob = totdolcob,
    vendedor = vendedor,
    empresa = empresa
)

fun Estadistica.toDatabase(): EstadisticaEntity = EstadisticaEntity(
    clivisit = clivisit,
    cntclientes = cntclientes,
    cntfacturas = cntfacturas,
    cntpedidos = cntpedidos,
    cntrecl = cntrecl,
    codcoord = codcoord,
    defdolTotneto = defdolTotneto,
    devdolTotneto = devdolTotneto,
    fechaEstad = fechaEstad,
    lomMontovtas = lomMontovtas,
    lomPrcvisit = lomPrcvisit,
    lomPrcvtas = lomPrcvtas,
    mtofacturas = mtofacturas,
    mtopedidos = mtopedidos,
    mtorecl = mtorecl,
    metavend = metavend,
    nombrevend = nombrevend,
    nomcoord = nomcoord,
    ppgdolTotneto = ppgdolTotneto,
    prcmeta = prcmeta,
    prcvisitas = prcvisitas,
    rlomMontovtas = rlomMontovtas,
    rlomPrcvisit = rlomPrcvisit,
    rlomPrcvtas = rlomPrcvtas,
    totdolcob = totdolcob,
    vendedor = vendedor,
    empresa = empresa
)

fun EstadisticaResponse.toDomain(): Estadistica = Estadistica(
    clivisit = clivisit ?: 0.0,
    cntclientes = cntclientes ?: 0.0,
    cntfacturas = cntfacturas ?: 0.0,
    cntpedidos = cntpedidos ?: 0.0,
    cntrecl = cntrecl ?: 0.0,
    codcoord = codcoord ?: "",
    defdolTotneto = defdolTotneto ?: 0.0,
    devdolTotneto = devdolTotneto ?: 0.0,
    fechaEstad = fechaEstad ?: "",
    lomMontovtas = lomMontovtas ?: 0.0,
    lomPrcvisit = lomPrcvisit ?: 0.0,
    lomPrcvtas = lomPrcvtas ?: 0.0,
    metavend = metavend ?: 0.0,
    mtofacturas = mtofacturas ?: 0.0,
    mtopedidos = mtopedidos ?: 0.0,
    mtorecl = mtorecl ?: 0.0,
    nombrevend = nombrevend ?: "",
    nomcoord = nomcoord ?: "",
    ppgdolTotneto = ppgdolTotneto ?: 0.0,
    prcmeta = prcmeta ?: 0.0,
    prcvisitas = prcvisitas ?: 0.0,
    rlomMontovtas = rlomMontovtas ?: 0.0,
    rlomPrcvisit = rlomPrcvisit ?: 0.0,
    rlomPrcvtas = rlomPrcvtas ?: 0.0,
    totdolcob = totdolcob ?: 0.0,
    vendedor = vendedor ?: ""
)
